auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "registry.k8s.io/kube-apiserver:v1.16.15": DOCKERHUB_USERNAME/kube-apiserver
  "registry.k8s.io/kube-controller-manager:v1.16.15": DOCKERHUB_USERNAME/kube-controller-manager
  "registry.k8s.io/kube-scheduler:v1.16.15": DOCKERHUB_USERNAME/kube-scheduler
  "registry.k8s.io/kube-proxy:v1.16.15": DOCKERHUB_USERNAME/kube-proxy
  "registry.k8s.io/cluster-proportional-autoscaler-amd64:1.6.0": DOCKERHUB_USERNAME/cluster-proportional-autoscaler-amd64
  "registry.k8s.io/pause-amd64:3.1": DOCKERHUB_USERNAME/pause-amd64
  "registry.k8s.io/pause:3.1": DOCKERHUB_USERNAME/pause
